apiVersion: v1
kind: Service
metadata:
  name: fastapi-callback
  namespace: sigun
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: sigun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fmelihh/sigun-istio-callback
          ports:
            - containerPort: 8000
