apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: sigun
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Refresh_Interval  5
        Rotate_Wait       30
        Docker_Mode       On
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name  http
        Match *
        Host  fastapi-callback.default.svc.cluster.local
        Port  80
        URI   /callback
        Format json
        Retry_Limit False
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
